---

- name: Add config include statement to amavisd.conf
  lineinfile:
    path: "{{ __postfix_amavisd_new_config_file }}"
    line: "Amavis::Conf::include_config_files(qw({{ __postfix_amavisd_new_exclusive_config_file }}));"
    insertbefore: '^1;\s*(\s*#.*)?$'
  when: __postfix_amavisd_new_config_file
  notify:
    - restart amavisd-new

- name: Install/update amavisd-new config file
  template:
    src: amavisd-new.conf.j2
    dest: "{{ __postfix_amavisd_new_exclusive_config_file }}"
  notify:
    - restart amavisd-new

- name: Schedule amavisd-new cron jobs
  cron:
    name: "{{ item.name | default(item.id) }}"
    cron_file: "{{ 'ansible_' ~ item.id if ansible_os_family != 'Solaris' else 'crontabs/' ~ item.user }}"
    user: "{{ item.user }}"
    hour: "{{ item.hour | default(omit) }}"
    minute: "{{ item.minute | default(omit) }}"
    day: "{{ item.day | default(omit) }}"
    month: "{{ item.month | default(omit) }}"
    weekday: "{{ item.weekday | default(omit) }}"
    job: "{{ item.job }}"
    state: "{{ item.state | default(omit) }}"
  loop: "{{ postfix_amavis_cron_jobs }}"
