---

- name: Include preinstallation tasks
  include_tasks: "{{ include_file }}"
  with_first_found:
    - files:
        - preinstall_{{ __postfix_os }}.yml
      skip: true
  loop_control:
    loop_var: include_file

- name: Install Postfix and related feature packages
  package:
    name: "{{ postfix_packages }}"

- name: Include amavisd-new configuration tasks
  include_tasks: amavisd-new.yml
  when: postfix_clamav or postfix_spamassassin

- name: Include ClamAV configuration tasks
  include_tasks: clamav.yml
  when: postfix_clamav and __postfix_clamav_config_merged

- name: Install/update Postfix config files
  template:
    src: "{{ item }}.j2"
    dest: "{{ postfix_config_dir }}/{{ item }}"
    backup: "{{ postfix_backup_configs }}"
  loop:
    - main.cf
    - master.cf
  notify:
    - restart postfix

- name: Include Postfix map build tasks
  import_tasks: maps.yml

- name: Include postinstallation tasks
  include_tasks: "{{ include_file }}"
  with_first_found:
    - files:
        - postinstall_{{ __postfix_os }}.yml
      skip: true
  loop_control:
    loop_var: include_file

# Perform whatever restarts are needed now, prevents double restart on first run
- name: Flush handlers
  meta: flush_handlers

- name: Ensure services are enabled and running
  service:
    name: "{{ item }}"
    enabled: yes
    state: started
  with_items: "{{ __postfix_services }}"
