---

- name: Install debconf packages
  apt:
    name:
      - debconf
      - debconf-utils

- name: Set client options in debconf
  debconf:
    name: mailman3
    question: "{{ item.question }}"
    value: "{{ item.value }}"
    vtype: "{{ item.vtype }}"
  with_items:
    - question: "postfix/main_mailer_type"
      value: "No configuration"
      vtype: "select"

- name: Create /etc/mailname
  copy:
    content: "{{ postfix_mailname }}"
    dest: /etc/mailname
  when: postfix_mailname is defined
  notify:
    - restart amavisd-new
    - restart postfix
